maine_codes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('mc_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mc_app/urls.py
"""Defines URL patterns for mc_app."""

from django.urls import path
from . import views

app_name = 'mc_app'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    # JavaScript Punctuation Quiz page.
    path('jsPunctuation/', views.jsPunctuation, name='jsPunctuation'),
    # Simple derivatives drill using MathJax.
    path('skill_selection/', views.skill_selection, name='skill_selection'),
    # Simple derivatives drill using MathJax.
    path('derivatives/', views.derivatives, name='derivatives'),
    # Simple derivatives drill using MathJax.
    path('fractionalCoefficients/', views.fractionalCoefficients, name='fractionalCoefficients'),
    # Record data afte a DerivativesSkills skill has been mastered.
    path('masteredRoutine/', views.masteredRoutine, name='masteredRoutine'),
    # Check the progress of all users.
    path('class_progress/', views.class_progress, name='class_progress'),
    # Check your progress.
    path('your_progress/', views.your_progress, name='your_progress'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration Page
    path('register/', views.register, name='register'),
    # Profile update page.
    path('profile/', views.profile, name='profile'),
    # Change password
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done')), name='password_change'),
]

mc_app/forms.py
from django import forms

class SelectSkillsForm(forms.Form):
    """This allows the user to select types of problems in the drills."""

    skillRadios = forms.CharField(widget=forms.RadioSelect)

mc_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core import serializers

from json import dumps

from .models import JavaScriptPunctuation
from .models import DerivativesSkills
from .models import UsersLatestSession
from .models import UserProgress

from .forms import SelectSkillsForm

import random


"""Next Steps: some of the percents on the DB are hard to get"""
"""is there a way to rationalize the mastered fields on the DB to make the code easier"""
"""Need to style all pages associated with the USER app"""
"""Need to host with DreamHost"""
"""Need to connect Google Sign In"""
"""Need to hook up Twilio for notifications"""

def index(request):
    """The home page for Maine codes."""
    return render(request, 'mc_app/index.html')

@login_required
def jsPunctuation(request):
    """The page for quizzes."""
    if request.method !='POST':
        questions = serializers.serialize('json', JavaScriptPunctuation.objects.filter(topic='punctuation'))
        context = {'questions': questions}
        return render(request, 'mc_app/jsPunctuation.html', context)
    else:
        id = request.POST['id']
        JavaScriptPunctuation.objects.filter(id=id).update(timesAnswered = request.POST['timesAnswered'], timesAnsweredCorrectly = request.POST['timesAnswered'], timesDistractor1 = request.POST['timesDistractor1'], timesDistractor2 = request.POST['timesDistractor2'], timesDistractor3 = request.POST['timesDistractor3'], timesDistractor4 = request.POST['timesDistractor4'])
    return render(request, 'mc_app/jsPunctuation.html')

@login_required
def skill_selection(request):
    if request.method != 'POST':
        progressObj = serializers.serialize('json', UserProgress.objects.filter(progressForUser=request.user))
        context = {'progressObj': progressObj}
        return render(request, 'mc_app/skill_selection.html', context)
    else:
        print(request.user)
        sessionObj = serializers.serialize('json', UsersLatestSession.objects.filter(sessionUser=request.user))
        print(sessionObj)
        form = SelectSkillsForm(data=request.POST)
        if form.is_valid():
            selection = form.cleaned_data["skillRadios"]
            print("This is selection: ")
            print(selection)
        else:
            selection = 'basicDerivatives'
        skillObj = serializers.serialize('json', DerivativesSkills.objects.filter(skillName=selection))
        print(skillObj)
        progressObj = serializers.serialize('json', UserProgress.objects.filter(progressForUser=request.user))
        context = {'selection': selection, 'sessionObj':sessionObj, 'skillObj': skillObj, 'progressObj': progressObj}
        return render(request, 'mc_app/derivatives.html', context )

def masteredRoutine(request):
    """Update the database when a user has mastered a quiz."""
    if request.method != 'POST':
        print("This is not a post")
    else:
        DerivativesSkills.objects.filter(skillName=request.POST["skillName"]).update(timesAttempted = request.POST['timesAttempted'], timesMastered = request.POST['timesMastered'], totalQuestionsAsked = request.POST['totalQuestionsAsked'], totalQuestionsAnsweredCorrectly = request.POST['totalQuestionsAnsweredCorrectly'], longestStreak = request.POST['longestStreak'], percentCorrect = request.POST['percentCorrect'])
        UserProgress.objects.filter(progressForUser=request.user).update(totalSkillsMastered = request.POST['totalSkillsMastered'], totalQuestionsAttempted = request.POST['progressTotalQuestionsAttempted'], totalQuestionsAnsweredCorrectly = request.POST['progressTotalQuestionsAnsweredCorrectly'], longestStreak = request.POST['progressLongestStreak'], percentCorrect = request.POST['progressPercentCorrect'])
        if request.POST["skillName"] == "basicDerivatives":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredBasicDerivatives = True, basicDerivativesMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredNegativeCoefficients = True, negativeCoefficientsMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "basicMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredBasicMix = True, basicMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeExponents":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredNegativeExponents = True, negativeExponentsMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "fractionalExponents":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredFractionalExponents = True, fractionalExponentsMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "advancedMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeExponentsAndCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeExponentsAndFractionalCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeExponentsBasicMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeExponentsAdavancedMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "fractionalExponentsAndNegativeCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "fractionalExponentsAndFractionalCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "fractionalExponentsBasicMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "fractionalExponentsAdavancedMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeFractionalExponents":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredFractionalExponents = True, fractionalExponentsMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeFractionalExponentsAndNegativeCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeFractionalExponentsAndFractionalCoefficients":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeFractionalExponentsBasicMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
        elif request.POST["skillName"] == "negativeFractionalExponentsAdavancedMix":
            UserProgress.objects.filter(progressForUser=request.user).update(masteredAdvancedMix = True, advancedMixMaxCorrect = request.POST['progressMaxCorrect'])
    """This page does not actually get rendered, but it throws an error wihtout any html"""
    return render(request, 'mc_app/derivatives.html')

def masteredMessage(request):
    """This shows a message when user has mastered a skill."""
    if request.method != 'POST':
        print("This is not a post")
    else:
        print("This is a post")
    return render(request, 'mc_app/skill_selection.html')

@login_required
def class_progress(request):
    if request.method != 'POST':
        progressData = UserProgress.objects.all()
        context = {'progressData': progressData}
        return render(request, 'mc_app/class_progress.html', context)
    else:
        print("This was a POST! Should be impossible!")

    return render(request, 'mc_app/class_progress.html', context)

@login_required
def your_progress(request):
    if request.method != 'POST':
        progressData = UserProgress.objects.get(progressForUser=request.user)
        context = {'progressData': progressData}
        return render(request, 'mc_app/your_progress.html', context)
    else:
        print("This was a POST! Should be impossible!")

    return render(request, 'mc_app/your_progress.html', context)


def derivatives(request):
    print("Derivatives works!")
    functions = "first";
    context = {'functions': functions}
    return render(request, 'mc_app/derivatives.html', context)

def fractionalCoefficients(request):
    print("FC works!")
    functions = "first";
    context = {'functions': functions}

mc_app/templates/mc_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--MathJax-->
    <script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom Syles -->
    <link rel="stylesheet" type="text/css" href="{% static 'mc_app/style.css' %}" />
    <title>Maine Codes</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'mc_app:index' %}">Home<span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'mc_app:skill_selection' %}">Calculus Skills</a>
          <a class="nav-item nav-link" href="{% url 'mc_app:jsPunctuation' %}">Coding Quizzes</a>
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'mc_app:your_progress' %}">Your Progress</a>
            {% if user.username == 'mcnalj'%}
              <a class="nav-item nav-link" href="{% url 'mc_app:class_progress' %}">Class Progress</a>
            {% endif %}
            <a class="nav-item nav-link" href="{% url 'users:logout' %}">Log out</a>
            <a class="nav-link" href="{% url 'users:password_change' %}">Change Password</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
            <a class="nav-item nav-link" href="{% url 'users:login' %}">Log in</a>
            <a class="nav-item nav-link" href="{% url 'password_reset' %}">Reset Password</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <main>

      {% block content %}{% endblock content %}

    </main><!-- /.container -->

    <!-- Bootstrap CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

mc_app/templates/mc_app/boostrap_jumbotron.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}
<h1>Maine Codes</h1>
  <p>A gallery of CBHS coders's work</p>

<!-- There is no perfect way to manage the height of a jumbotron image -->
  <div class="jumbotron">
    <h1 class="display-4">Maine Codes</h1>
    <p class="lead">A gallery of CBHS coders's work</p>
    <p>This is not a lead, just a regular paragraph</p>
    <img src="{% static 'mc_app/images/crew_winter_hike.jpeg' %}" class="d-block w-100" alt="McNally Crew hiking through the snowy woods">
  </div>
  <!-- This seems like the best. It resizes the image, keeps it centered. Trick is setting the appropriate minimum height. -->
  <div class="jumbotron" style="background: url('{% static "mc_app/images/crew_winter_hike.jpeg" %}') center center / cover no-repeat; min-height: 400px">
    <h1 class="display-4">Maine Codes</h1>
    <p class="lead">A gallery of CBHS coders's work</p>
    <p>This is not a lead, just a regular paragraph</p>
  </div>

  <div class="jumbotron" style="background-image: url('{% static "mc_app/images/crew_winter_hike.jpeg" %}'); background-size: cover; background-height: 100%; min-height: 400px;">
    <h1 class="display-4">Maine Codes</h1>
    <p class="lead">A gallery of CBHS coders's work</p>
    <p>This is not a lead, just a regular paragraph</p>
  </div>

{% endblock content %}

mc_app/templates/mc_app/bootstrap_cards.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}
<h1>Maine Codes</h1>
  <p>A gallery of CBHS coders's work</p>

  <div class="card" style="width: 50%;">
    <h5 class="card-header">2020</h5>
    <img src="{% static 'mc_app/images/crew_winter_hike.jpeg' %}" class="card-img-top" alt="McNally Crew hiking through the snowy woods">
    <div class="card-body">
      <h5 class="card-title">Ice Quest</h5>
      <p class="card-text">McNally Crew summiting Pleasant Mountain.</p>
      <a href="#" class="btn btn-primary">More pics</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="card" style="width: 18rem;">
      <h5 class="card-header">2020</h5>
      <img src="{% static 'mc_app/images/crew_winter_hike.jpeg' %}" class="card-img-top" alt="McNally Crew hiking through the snowy woods">
      <div class="card-body">
        <h5 class="card-title">Ice Quest</h5>
        <p class="card-text">McNally Crew summiting Pleasant Mountain.</p>
        <a href="#" class="btn btn-primary">More pics</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card" style="width: 18rem;">
      <h5 class="card-header">2020</h5>
      <img src="{% static 'mc_app/images/crew_winter_hike.jpeg' %}" class="card-img-top" alt="McNally Crew hiking through the snowy woods">
      <div class="card-body">
        <h5 class="card-title">Ice Quest</h5>
        <p class="card-text">McNally Crew summiting Pleasant Mountain.</p>
        <a href="#" class="btn btn-primary">More pics</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

mc_app/templates/mc_app/bootstrap_carousel.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}
<p>Maine Codes</p>
  <p>Needs research to figure out why images don't change.</p>
  <div id ="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'mc_app/images/crew_winter_hike.jpeg' %}" class="d-block w-100" alt="McNally Crew hiking through the snowy woods">
      </div>
      <div class="carousel-item">
        <img src="{% static 'mc_app/images/cherry_blossom.JPG' %}" class="d-block w-100" alt="cherry blossom close-up">
      </div>
      <div class="carousel-item">
        <img src="{% static 'mc_app/images/quest_boat.JPG' %}" class="d-block w-100" alt="Quest boat viewed from pop passing Fort Gorges">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock content %}

mc_app/templates/mc_app/class_progress.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}
<h4>Class Progress</h4>
<div class="table-responsive">
  <table class="table table-striped table-sm text-center ">
    <thead>
      <tr>
        <th scope="col">Username</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Attempted</th>
        <th scope="col">Correct</th>
        <th scope="col">Basic Derivatives</th>
        <th scope="col">Negative Coefficients</th>
        <th scope="col">Fractional Coefficients</th>
        <th scope="col">Basic Mix</th>
        <th scope="col">Advanced Mix</th>
        <th scope="col">Negative Exponents</th>
        <th scope="col">Fractional Exponents</th>
        <th scope="col">Negative Fractional Exponents</th>        

      </tr>
    </thead>
    <tbody>
      {% for student in progressData %}
        <tr>
          <th scope="row">{{ student.progressForUser.username }}</th>
          <td>{{student.progressForUser.first_name}}</td>
          <td>{{student.progressForUser.last_name}}</td>
          <td>{{student.totalQuestionsAttempted}}</td>
          <td>{{student.totalQuestionsAnsweredCorrectly}}</td>
          {% if student.masteredBasicDerivatives %}
            <td class="table-success">{{student.masteredBasicDerivatives}}</td>
          {% else %}
            <td>{{student.masteredBasicDerivatives}}</td>
          {% endif %}
          {% if student.masteredNegativeCoefficients %}
            <td class="table-success">{{student.masteredNegativeCoefficients}}</td>
          {% else %}
            <td>{{student.masteredNegativeCoefficients}}</td>
          {% endif %}
          {% if student.masteredFractionalCoefficients %}
            <td class="table-success">{{student.masteredFractionalCoefficients}}</td>
          {% else %}
            <td>{{student.masteredFractionalCoefficients}}</td>
          {% endif %}
          {% if student.masteredBasicMix %}
            <td class="table-success">{{student.masteredBasicMix}}</td>
          {% else %}
            <td>{{student.masteredBasicMix}}</td>
          {% endif %}
          {% if student.masteredAdvancedMix %}
            <td class="table-success">{{student.masteredAdvancedMix}}</td>
          {% else %}
            <td>{{student.masteredAdvancedMix}}</td>
          {% endif %}
          {% if student.masteredNegativeExponents %}
            <td class="table-success">{{student.masteredNegativeExponents}}</td>
          {% else %}
            <td>{{student.masteredNegativeExponents}}</td>
          {% endif %}
          {% if student.masteredFractionalExponents %}
            <td class="table-success">{{student.masteredFractionalExponents}}</td>
          {% else %}
            <td>{{student.masteredFractionalExponents}}</td>
          {% endif %}
          {% if student.masteredNegativeFractionalExponents %}
            <td class="table-success">{{student.masteredNegativeFractionalExponents}}</td>
          {% else %}
            <td>{{student.masteredNegativeFractionalExponents}}</td>
          {% endif %}

        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

mc_app/templates/mc_app/fractionalCoefficients.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}

<div id="questionCard" class="card mx-auto border border-dark mt-5" style="width: 80%">
  <div class="card-header" id="topic">FRACTIONAL COEFFICIENTS</div>
  <div class="card-body text-center">
    <h4 class="card-title" id="question">Find the derivative of the given function:</h4>
    </br>
    <div id="mathEquation" style="font-size: 2rem;">\(f(x) = 6x^2\)</div>
    </br>
    </br>
    <form id="answer_form" class="card-footer mx-auto" style="width: 100%;" method="post">
      {% csrf_token %}
      </br>
      <label for="answer" style="font-size: 2rem;">\(f'(x) = \)</label>
      <input type='text' id="answer" name="answer" onfocus="this.placeholder=''" style="font-size: 2rem; text-align: center;" placeholder="3x^2" autocomplete="off">
      </br>
      <p id="answerMessage" style="font-size: .75em; color:red; visibility:hidden;">Correct!</p>
      </br>
      <button id="answerButton" href="#" class="btn btn-primary" type="submit" style="width: 100%;">SUBMIT</button>
    </form>
  </div>
</div>

<script src="{% static 'mc_app/javascript/derivatives.js' %}"></script>

})

{% endblock content %}

mc_app/templates/mc_app/jsPunctuation.html
{% extends "mc_app/base.html" %}
{% load static %}
{% block content %}
<div class="card mx-auto border-dark mt-5" style="width: 80%">
  <div class="card-header" id="topic">PUNCTUATION</div>
  <div class="card-body text-center">
    <h4 class="card-title" id="question">Which one of these words is surrounded by quotation marks?</h4>

  <ul class="list-group list-group-flush text-center" style="font-size: 20pt">
    <li class="list-group-item"><span id="answer_a" class="code" style="font-family: monospace;">(quotes)</span></li>
    <li class="list-group-item"><span id="answer_b" class="code" style="font-family: monospace;">"quotes"</span></li>
    <li class="list-group-item"><span id="answer_c" class="code" style="font-family: monospace;">[quotes]</span></li>
    <li class="list-group-item"><span id="answer_d" class="code" style="font-family: monospace;">{quotes}</span></li>
  </ul>
  </div>
  <form id="answer_form" class="card-footer mx-auto" style="width: 100%;" method="post">
    {% csrf_token %}
    <button href="#" id="quizAnswerButton" class="btn btn-primary" type="submit" style="width: 100%;">NEXT</button>
  </form>
  <div>
    <a id="endQuiz" href="{% url 'mc_app:index' %}" class="btn btn-primary mt-2" style="width: 100%; visibility: hidden">HOME</a>
  </div>
</div>
<script>
    var originalQuestions = {{questions|safe}}
</script>
<script src="{% static 'mc_app/javascript/answer_questions.js' %}"></script>



{% endblock content %}